services:
  - name: nitter
    type: web
    plan: starter
    runtime: image
    image:
      url: ghcr.io/sekai-soft/nitter-self-contained
    envVars:
      - key: NITTER_ACCOUNTS_FILE
        value: /nitter-data/guest_accounts.json
      - key: DISABLE_REDIS
        value: "1"
      - key: REDIS_HOST
        value: nitter-redis
    region: oregon
    autoDeploy: true
    numInstances: 1
  - name: redis
    type: pserv
    runtime: image
    image: 
      url: redis:6-alpine
    disk:
      name: nitter-redis
      mountPath: /data

