services:
  - name: nitter
    type: web
    runtime: image
    image:
      url: ghcr.io/sekai-soft/nitter-self-contained
    plan: free
    envVars:
      - key: NITTER_ACCOUNTS_FILE
        value: /nitter-data/guest_accounts.json
      - key: DISABLE_REDIS
        value: "1"
      - key: REDIS_HOST
        value: nitter-redis
    healthCheckPath: /
    region: oregon
    disk:
      name: nitter-data
      mountPath: /nitter-data
      sizeGB: 1
    autoDeploy: true
    numInstances: 1
    notifyOnFail: true
    retryDelay: 5s
    retries: 3
